### ISSUE TITLE
Allow user to checkout to a custom branch instead of always master

### ISSUE THREAD

**Issue by vKongv** [seekinternational/github-release#2]
I realize that this library always checkout to `master` branch and compare it with the latest tag in `findCommitsDifference` function. This issue was found when I tried to run circle ci deployment on my feature branch and it did not publish any release as the latest release is identical with `master` branch.

What I wish to have is we can pass in a custom environment variable (let says `CURRENT_BRANCH`) and use that as the checkout branch instead of always `master`. 

I do some digging into the code and found that `findCommitsDifference` function is actually accepting a third params which is `base` that always default to `master` so we pass in the params like `findCommitsDifference(releases.pop(), build.repopath, process.env.CURRENT_BRANCH);` in `github.js gitWorkFlow function`.

**Comment by essame** [comment]
Resolved in https://github.com/seekinternational/github-release/pull/1
